//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.15 at 01:26:51 PM COT 
//


package engine.properties;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LayerProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayerProperties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.gamepoc.org/RenderProperties}LayerAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayerProperties")
public class LayerProperties {

    @XmlAttribute(name = "name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "depth")
    @XmlSchemaType(name = "anySimpleType")
    protected String depth;
    @XmlAttribute(name = "colorMode")
    protected String colorMode;
    @XmlAttribute(name = "ellipseMode")
    protected String ellipseMode;
    @XmlAttribute(name = "rectMode")
    protected String rectMode;
    @XmlAttribute(name = "imageMode")
    protected String imageMode;
    @XmlAttribute(name = "shapeMode")
    protected String shapeMode;
    @XmlAttribute(name = "textMode")
    protected String textMode;
    @XmlAttribute(name = "textureMode")
    protected String textureMode;
    @XmlAttribute(name = "renderMode")
    protected String renderMode;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepth(String value) {
        this.depth = value;
    }

    /**
     * Gets the value of the colorMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorMode() {
        if (colorMode == null) {
            return "RGB";
        } else {
            return colorMode;
        }
    }

    /**
     * Sets the value of the colorMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorMode(String value) {
        this.colorMode = value;
    }

    /**
     * Gets the value of the ellipseMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEllipseMode() {
        if (ellipseMode == null) {
            return "CENTER";
        } else {
            return ellipseMode;
        }
    }

    /**
     * Sets the value of the ellipseMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEllipseMode(String value) {
        this.ellipseMode = value;
    }

    /**
     * Gets the value of the rectMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRectMode() {
        if (rectMode == null) {
            return "CORNER";
        } else {
            return rectMode;
        }
    }

    /**
     * Sets the value of the rectMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRectMode(String value) {
        this.rectMode = value;
    }

    /**
     * Gets the value of the imageMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageMode() {
        if (imageMode == null) {
            return "CORNER";
        } else {
            return imageMode;
        }
    }

    /**
     * Sets the value of the imageMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageMode(String value) {
        this.imageMode = value;
    }

    /**
     * Gets the value of the shapeMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShapeMode() {
        if (shapeMode == null) {
            return "CORNER";
        } else {
            return shapeMode;
        }
    }

    /**
     * Sets the value of the shapeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShapeMode(String value) {
        this.shapeMode = value;
    }

    /**
     * Gets the value of the textMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextMode() {
        if (textMode == null) {
            return "MODEL";
        } else {
            return textMode;
        }
    }

    /**
     * Sets the value of the textMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextMode(String value) {
        this.textMode = value;
    }

    /**
     * Gets the value of the textureMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureMode() {
        if (textureMode == null) {
            return "IMAGE";
        } else {
            return textureMode;
        }
    }

    /**
     * Sets the value of the textureMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureMode(String value) {
        this.textureMode = value;
    }

    /**
     * Gets the value of the renderMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenderMode() {
        if (renderMode == null) {
            return "NORMAL";
        } else {
            return renderMode;
        }
    }

    /**
     * Sets the value of the renderMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenderMode(String value) {
        this.renderMode = value;
    }

}
