//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.15 at 01:26:51 PM COT 
//


package engine.properties;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gamepoc.renderproperties package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content consists of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RenderProperties_QNAME = new QName("http://www.gamepoc.org/RenderProperties", "renderProperties");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gamepoc.renderproperties
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RenderProperties }
     * 
     */
    public RenderProperties createRenderProperties() {
        return new RenderProperties();
    }

    /**
     * Create an instance of {@link LayerProperties }
     * 
     */
    public LayerProperties createLayerProperties() {
        return new LayerProperties();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RenderProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gamepoc.org/RenderProperties", name = "renderProperties")
    public JAXBElement<RenderProperties> createRenderProperties(RenderProperties value) {
        return new JAXBElement<RenderProperties>(_RenderProperties_QNAME, RenderProperties.class, null, value);
    }

}
