//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.15 at 01:26:51 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gamepoc.org/RenderProperties")
package engine.properties;
