//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.15 at 01:26:51 PM COT 
//


package engine.properties;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RenderProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RenderProperties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="layer" type="{http://www.gamepoc.org/RenderProperties}LayerProperties" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.gamepoc.org/RenderProperties}RenderAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RenderProperties", propOrder = {
    "layer"
})
public class RenderProperties {

    @XmlElement(required = true)
    protected List<LayerProperties> layer;
    @XmlAttribute(name = "colorMode")
    protected String colorMode;
    @XmlAttribute(name = "ellipseMode")
    protected String ellipseMode;
    @XmlAttribute(name = "rectMode")
    protected String rectMode;
    @XmlAttribute(name = "imageMode")
    protected String imageMode;
    @XmlAttribute(name = "shapeMode")
    protected String shapeMode;
    @XmlAttribute(name = "textMode")
    protected String textMode;
    @XmlAttribute(name = "textureMode")
    protected String textureMode;
    @XmlAttribute(name = "renderMode")
    protected String renderMode;

    /**
     * Gets the value of the layer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LayerProperties }
     * 
     * 
     */
    public List<LayerProperties> getLayer() {
        if (layer == null) {
            layer = new ArrayList<LayerProperties>();
        }
        return this.layer;
    }

    /**
     * Gets the value of the colorMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorMode() {
        if (colorMode == null) {
            return "RGB";
        } else {
            return colorMode;
        }
    }

    /**
     * Sets the value of the colorMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorMode(String value) {
        this.colorMode = value;
    }

    /**
     * Gets the value of the ellipseMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEllipseMode() {
        if (ellipseMode == null) {
            return "CENTER";
        } else {
            return ellipseMode;
        }
    }

    /**
     * Sets the value of the ellipseMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEllipseMode(String value) {
        this.ellipseMode = value;
    }

    /**
     * Gets the value of the rectMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRectMode() {
        if (rectMode == null) {
            return "CORNER";
        } else {
            return rectMode;
        }
    }

    /**
     * Sets the value of the rectMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRectMode(String value) {
        this.rectMode = value;
    }

    /**
     * Gets the value of the imageMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageMode() {
        if (imageMode == null) {
            return "CORNER";
        } else {
            return imageMode;
        }
    }

    /**
     * Sets the value of the imageMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageMode(String value) {
        this.imageMode = value;
    }

    /**
     * Gets the value of the shapeMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShapeMode() {
        if (shapeMode == null) {
            return "CORNER";
        } else {
            return shapeMode;
        }
    }

    /**
     * Sets the value of the shapeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShapeMode(String value) {
        this.shapeMode = value;
    }

    /**
     * Gets the value of the textMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextMode() {
        if (textMode == null) {
            return "MODEL";
        } else {
            return textMode;
        }
    }

    /**
     * Sets the value of the textMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextMode(String value) {
        this.textMode = value;
    }

    /**
     * Gets the value of the textureMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureMode() {
        if (textureMode == null) {
            return "IMAGE";
        } else {
            return textureMode;
        }
    }

    /**
     * Sets the value of the textureMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureMode(String value) {
        this.textureMode = value;
    }

    /**
     * Gets the value of the renderMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenderMode() {
        if (renderMode == null) {
            return "NORMAL";
        } else {
            return renderMode;
        }
    }

    /**
     * Sets the value of the renderMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenderMode(String value) {
        this.renderMode = value;
    }

}
